
import java.awt.Font;
import java.io.IOException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class TelaFazerAluguel extends javax.swing.JFrame {

    /**
     * Creates new form FazerAluguel
     */
    public TelaFazerAluguel() {
        initComponents();
        DefaultListModel model = new DefaultListModel();
            
        for(int i=0;i <TelaInicial.listaCarro.size();i++){
            if(TelaInicial.listaCarro.get(i).getSituacao() == 0){
                model.addElement(TelaInicial.listaCarro.get(i).getPlaca());
            }
        }
        listaCarrosDisponiveis.setModel(model);
        this.setLocation(450,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelTelaInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldCPF = new javax.swing.JTextField();
        radioDiaria = new javax.swing.JRadioButton();
        radioKM = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        botaoFazerAluguel = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCarrosDisponiveis = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        formatedDataFim = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetalhes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTelaInicial.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelTelaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelaInicial.setText("Alugar Carro");

        jLabel1.setText("CPF/CNPJ:");

        buttonGroup1.add(radioDiaria);
        radioDiaria.setText("Diária");

        buttonGroup1.add(radioKM);
        radioKM.setText("Kilometragem");

        jLabel3.setText("Tipo de locação:");

        botaoFazerAluguel.setText("Alugar Carro");
        botaoFazerAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazerAluguelActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel4.setText("Carros Disponíveis:");

        listaCarrosDisponiveis.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaCarrosDisponiveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCarrosDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCarrosDisponiveisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCarrosDisponiveis);

        jLabel2.setText("Data de Devolução:");

        formatedDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        txtAreaDetalhes.setEditable(false);
        txtAreaDetalhes.setBackground(new java.awt.Color(240, 240, 240));
        txtAreaDetalhes.setColumns(5);
        txtAreaDetalhes.setLineWrap(true);
        txtAreaDetalhes.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetalhes);

        jLabel5.setText("Detalhes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoFazerAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtFieldCPF)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(radioKM)
                    .addComponent(radioDiaria)
                    .addComponent(jLabel2)
                    .addComponent(formatedDataFim))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formatedDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioDiaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioKM))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFazerAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFazerAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFazerAluguelActionPerformed
        
        if(txtFieldCPF.getText()==null){
            //EXIBE MENSAGEM DE ERRO - CPF NAO DIGITADO
        }else{
            int auxCli = TelaInicial.buscaCliente(TelaInicial.listaCliente, Integer.parseInt(txtFieldCPF.getText()));
            int auxCar = TelaInicial.buscaCarro(TelaInicial.listaCarro, listaCarrosDisponiveis.getSelectedValue().toString());
            if(auxCli != -1){
                if(TelaInicial.listaCliente.get(auxCli).getDivida() == 0.0){
                        //tratamendo ta variavel data final
                        LocalDate LDATA = LocalDate.of(Integer.parseInt(formatedDataFim.getText().substring(6,10)),
                                                       Integer.parseInt(formatedDataFim.getText().substring(3,5)),
                                                       Integer.parseInt(formatedDataFim.getText().substring(0,2))
                                                       );
                        //BLOCO DE CRIACAO DE OBJETO ALUGUEL + SETA PRO ARRAYLIST ALUGUEL
                        int tipoAux;
                        if(radioDiaria.isSelected()){
                            tipoAux = 1;
                            //altera o carro para indisponivel
                            
                            TelaInicial.listaCarro.get(auxCar).setSituacao(1);
                            TelaInicial.listaAluguel.add(
                                                        new Aluguel(Integer.parseInt(txtFieldCPF.getText()),tipoAux,
                                                        listaCarrosDisponiveis.getSelectedValue().toString(),
                                                        LocalDate.now(),
                                                        LDATA)
                                                        );
                        
                        }else if(radioKM.isSelected()){
                            tipoAux = 2;
                            TelaInicial.listaCarro.get(auxCar).setSituacao(1);
                            TelaInicial.listaAluguel.add(
                                                        new Aluguel(Integer.parseInt(txtFieldCPF.getText()),tipoAux,
                                                        listaCarrosDisponiveis.getSelectedValue().toString(),
                                                        LocalDate.now(),
                                                        LDATA)
                                                        );
                        }
                        //FIM DO BLOCO
                }else{
                    //ERRO CLIENTE COM DIVIDA
                }   
            }
        }
    }//GEN-LAST:event_botaoFazerAluguelActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
        try {
            new TelaInicial().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaFazerAluguel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void listaCarrosDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCarrosDisponiveisMouseClicked
        String placaAux = listaCarrosDisponiveis.getSelectedValue().toString();
        int info = TelaInicial.buscaCarro(TelaInicial.listaCarro,placaAux);
        txtAreaDetalhes.setFont(new Font("Arial",Font.PLAIN,12));
                    txtAreaDetalhes.setText("Modelo: \n" +TelaInicial.listaCarro.get(info).getDescricao()
                            +"\nKm: \n"+TelaInicial.listaCarro.get(info).getKm()
                            +"\nPreço por KM: \nR$ "+TelaInicial.listaCarro.get(info).getPrecoKm()
                            +"\nPreço por dia: \nR$ "+TelaInicial.listaCarro.get(info).getTaxaDiaria()
                            +"\nObservação: \n"+TelaInicial.listaCarro.get(info).getObservacao()+"\n"
                            );
    }//GEN-LAST:event_listaCarrosDisponiveisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFazerAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFazerAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFazerAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFazerAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaFazerAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFazerAluguel;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField formatedDataFim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTelaInicial;
    private javax.swing.JList listaCarrosDisponiveis;
    private javax.swing.JRadioButton radioDiaria;
    private javax.swing.JRadioButton radioKM;
    private javax.swing.JTextArea txtAreaDetalhes;
    private javax.swing.JTextField txtFieldCPF;
    // End of variables declaration//GEN-END:variables
}
