
import java.io.IOException;
import java.time.LocalDate;
import java.time.Period;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
public class TelaDevolucao extends javax.swing.JFrame {

    /**
     * Creates new form TelaDevolucao
     */
    public TelaDevolucao() {
        initComponents();
        this.setLocation(450,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTelaInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtFieldCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCarrosAlugados = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        botaoDevolverCarro = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoPesquisa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelDataInicial = new javax.swing.JLabel();
        labelDataFim = new javax.swing.JLabel();
        labelTipoLocacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTelaInicial.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelTelaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelaInicial.setText("Devolver Carro");

        jLabel1.setText("CPF/CNPJ:");

        listaCarrosAlugados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaCarrosAlugados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaCarrosAlugados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaCarrosAlugadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaCarrosAlugados);

        jLabel2.setText("Carros Alugados:");

        botaoDevolverCarro.setText("Devolver Carro");
        botaoDevolverCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDevolverCarroActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoPesquisa.setText("Pesquisar");
        botaoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaActionPerformed(evt);
            }
        });

        jLabel4.setText("Detalhes:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setFocusable(false);

        labelDataInicial.setText(" ");

        labelDataFim.setText(" ");

        labelTipoLocacao.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDataInicial)
                    .addComponent(labelDataFim)
                    .addComponent(labelTipoLocacao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDataFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTipoLocacao)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoDevolverCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(109, 109, 109))
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoDevolverCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaActionPerformed
        
        DefaultListModel model = new DefaultListModel();
        int alugAux = TelaInicial.buscaAluguelCPF(TelaInicial.listaAluguel, Integer.parseInt(txtFieldCPF.getText()));
        //int carAux = TelaInicial.buscaCarro(TelaInicial.listaCarro, listaCarrosAlugados.getSelectedValue().toString());
        
        for(int i=0;i < TelaInicial.listaAluguel.size();i++){
            if(TelaInicial.listaAluguel.get(i).getCpf() == Integer.parseInt(txtFieldCPF.getText())){
                if(TelaInicial.listaAluguel.get(i).getStatus() == 0){
                    model.addElement(TelaInicial.listaAluguel.get(i).getPlaca());    
                }
            }
        }
        listaCarrosAlugados.setModel(model);
    }//GEN-LAST:event_botaoPesquisaActionPerformed
        
    private void botaoDevolverCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDevolverCarroActionPerformed
        Float divida;
        int alugAux,carAux,cliAux;
        alugAux = TelaInicial.buscaAluguel(TelaInicial.listaAluguel, Integer.parseInt(txtFieldCPF.getText()), listaCarrosAlugados.getSelectedValue().toString());
        carAux = TelaInicial.buscaCarro(TelaInicial.listaCarro, listaCarrosAlugados.getSelectedValue().toString());
        cliAux = TelaInicial.buscaCliente(TelaInicial.listaCliente, TelaInicial.listaAluguel.get(alugAux).getCpf());
        
        if(TelaInicial.listaAluguel.get(alugAux).getTipoLocacao() == 1){
            Period periodo = Period.between(TelaInicial.listaAluguel.get(alugAux).getDataInicio()
                        ,TelaInicial.listaAluguel.get(alugAux).getDataFim());
            divida = periodo.getDays() * TelaInicial.listaCarro.get(carAux).getTaxaDiaria();
            TelaInicial.listaCliente.get(cliAux).setDivida(TelaInicial.listaCliente.get(cliAux).getDivida()+divida);
            TelaInicial.listaCarro.get(carAux).setSituacao(0);
            TelaInicial.listaAluguel.get(alugAux).setStatus(1);
            int KMAtual = Integer.parseInt(JOptionPane.showInputDialog("Digite o KM atual do veículo"));
            if(KMAtual <= TelaInicial.listaCarro.get(carAux).getKm()){
                JOptionPane.showMessageDialog(null,"KM inserido menor que o atual do veículo!","Erro no KM!",JOptionPane.ERROR_MESSAGE);
            }else{
                TelaInicial.listaCarro.get(carAux).setKm(KMAtual);
            }
            
        }else if(TelaInicial.listaAluguel.get(alugAux).getTipoLocacao() == 2){
            int KMAtual = Integer.parseInt(JOptionPane.showInputDialog("Digite o KM atual do veículo"));
            if(KMAtual <= TelaInicial.listaCarro.get(carAux).getKm()){
                JOptionPane.showMessageDialog(null,"KM inserido menor que o atual do veículo!","Erro no KM!",JOptionPane.ERROR_MESSAGE);
            }else{
                divida = (KMAtual - TelaInicial.listaCarro.get(carAux).getKm()) * TelaInicial.listaCarro.get(carAux).getPrecoKm();            
                System.out.println("Km atual "+KMAtual);
                System.out.println("Divida - "+divida);
                TelaInicial.listaCliente.get(cliAux).setDivida(TelaInicial.listaCliente.get(cliAux).getDivida()+divida);
                TelaInicial.listaCarro.get(carAux).setSituacao(0);
                TelaInicial.listaCarro.get(carAux).setKm(KMAtual);
                TelaInicial.listaAluguel.get(alugAux).setStatus(1);
            }
        }
    }//GEN-LAST:event_botaoDevolverCarroActionPerformed

    private void listaCarrosAlugadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaCarrosAlugadosMouseClicked
        String placaAux = listaCarrosAlugados.getSelectedValue().toString();
        int alugAux = TelaInicial.buscaAluguelPLACA(TelaInicial.listaAluguel,placaAux);
        labelDataInicial.setText(TelaInicial.listaAluguel.get(alugAux).getDataInicio().toString());
        labelDataFim.setText(TelaInicial.listaAluguel.get(alugAux).getDataFim().toString());
        if(TelaInicial.listaAluguel.get(alugAux).getTipoLocacao() == 1){
            labelTipoLocacao.setText("Locação por diária");
        }else if(TelaInicial.listaAluguel.get(alugAux).getTipoLocacao() == 2){
            labelTipoLocacao.setText("Locação por KMs");
        }
    }//GEN-LAST:event_listaCarrosAlugadosMouseClicked

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
        try {
            new TelaInicial().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaDevolucao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDevolverCarro;
    private javax.swing.JButton botaoPesquisa;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataFim;
    private javax.swing.JLabel labelDataInicial;
    private javax.swing.JLabel labelTelaInicial;
    private javax.swing.JLabel labelTipoLocacao;
    private javax.swing.JList listaCarrosAlugados;
    private javax.swing.JTextField txtFieldCPF;
    // End of variables declaration//GEN-END:variables
}
