
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaRelatorios extends javax.swing.JFrame {

    public TelaRelatorios() {
        initComponents();
        this.setLocation(450,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        labelTelaInicial = new javax.swing.JLabel();
        botaoClienteRelatorio = new javax.swing.JRadioButton();
        botaoCarroRelatorio = new javax.swing.JRadioButton();
        botaoAluguelRelatorio = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRelatorios = new javax.swing.JTextArea();
        botaoGerarRelatorio = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTelaInicial.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        labelTelaInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelaInicial.setText("Relatorios");

        buttonGroup1.add(botaoClienteRelatorio);
        botaoClienteRelatorio.setText("Clientes");

        buttonGroup1.add(botaoCarroRelatorio);
        botaoCarroRelatorio.setText("Carros");
        botaoCarroRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCarroRelatorioActionPerformed(evt);
            }
        });

        buttonGroup1.add(botaoAluguelRelatorio);
        botaoAluguelRelatorio.setText("Alugueis");

        txtAreaRelatorios.setEditable(false);
        txtAreaRelatorios.setColumns(12);
        txtAreaRelatorios.setRows(5);
        txtAreaRelatorios.setTabSize(5);
        jScrollPane1.setViewportView(txtAreaRelatorios);

        botaoGerarRelatorio.setText("Gerar Relatorio");
        botaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerarRelatorioActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoClienteRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(botaoCarroRelatorio)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAluguelRelatorio)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoGerarRelatorio)
                        .addGap(80, 80, 80)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTelaInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoClienteRelatorio)
                    .addComponent(botaoCarroRelatorio)
                    .addComponent(botaoAluguelRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(botaoGerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCarroRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCarroRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCarroRelatorioActionPerformed

    private void botaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerarRelatorioActionPerformed
        if(botaoClienteRelatorio.isSelected()){
            txtAreaRelatorios.setText(null);
            for(int i=0;i <TelaInicial.listaCliente.size();i++){
                
                txtAreaRelatorios.setFont(new Font("Arial",Font.PLAIN,12));
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append("Cliente "+(i+1)+"\n");
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append("Nome: "+TelaInicial.listaCliente.get(i).getNome()
                        +"\nCPF "+TelaInicial.listaCliente.get(i).getCpf()
                        +"\nEndereço: "+TelaInicial.listaCliente.get(i).getEnd()
                        +"\nTel: "+TelaInicial.listaCliente.get(i).getTel()
                        +"\nDivida: "+TelaInicial.listaCliente.get(i).getDivida()+"\n"
                );
            }    
        }else if(botaoCarroRelatorio.isSelected()){
            txtAreaRelatorios.setText(null);
            for(int i=0;i <TelaInicial.listaCarro.size();i++){
                
                txtAreaRelatorios.setFont(new Font("Arial",Font.PLAIN,12));
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append("Carro "+(i+1)+"\n");
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append(TelaInicial.listaCarro.get(i).getPlaca()
                        +"\n"+TelaInicial.listaCarro.get(i).getDescricao()
                        +"\n"+TelaInicial.listaCarro.get(i).getSituacao()
                        +"\n"+TelaInicial.listaCarro.get(i).getKm()
                        +"\n"+TelaInicial.listaCarro.get(i).getPrecoKm()
                        +"\n"+TelaInicial.listaCarro.get(i).getTaxaDiaria()
                        +"\n"+TelaInicial.listaCarro.get(i).getObservacao()+"\n"
                );
            }
            
        }else if(botaoAluguelRelatorio.isSelected()){
            txtAreaRelatorios.setText(null);
            for(int i=0;i <TelaInicial.listaAluguel.size();i++){
                String tipoLoc,statusLoc;
                if(TelaInicial.listaAluguel.get(i).getTipoLocacao() == 1){
                    tipoLoc = "Locação por dia";
                }else{
                    tipoLoc = "Locação por KM";
                }
                if(TelaInicial.listaAluguel.get(i).getStatus() == 1){
                    statusLoc = "Devolvido";
                }else{
                    statusLoc = "Não devolvido";
                }
                
                
                txtAreaRelatorios.setFont(new Font("Arial",Font.PLAIN,12));
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append("Aluguel "+(i+1)+"\n");
                txtAreaRelatorios.append("-----------------\n");
                txtAreaRelatorios.append("CPF/CNPJ: "+String.valueOf(TelaInicial.listaAluguel.get(i).getCpf())
                        +"\n"+tipoLoc
                        +"\nPlaca: "+TelaInicial.listaAluguel.get(i).getPlaca()
                        +"\nData do aluguel: "+TelaInicial.listaAluguel.get(i).getDataInicio()
                        +"\nData de devolução: "+TelaInicial.listaAluguel.get(i).getDataFim()
                        +"\nStatus: "+statusLoc+"\n"
                );
            }
        }
    }//GEN-LAST:event_botaoGerarRelatorioActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        try {
            this.dispose();
            new TelaInicial().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botaoAluguelRelatorio;
    private javax.swing.JRadioButton botaoCarroRelatorio;
    private javax.swing.JRadioButton botaoClienteRelatorio;
    private javax.swing.JButton botaoGerarRelatorio;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelTelaInicial;
    private javax.swing.JTextArea txtAreaRelatorios;
    // End of variables declaration//GEN-END:variables
}
